### ISSUE TITLE
Tar and zip archivers read entries fully into memory

### ISSUE THREAD

**Issue by mrdziuban** [lhns/fs2-compress#77] opened 2024-01-02 21:52 UTC
The use of `chunkAll` [in `TarArchiver#archive`](https://github.com/lhns/fs2-compress/blob/main/tar/src/main/scala/de/lhns/fs2/compress/Tar.scala#L67) and [in `ZipArchiver#archive`](https://github.com/lhns/fs2-compress/blob/main/zip/src/main/scala/de/lhns/fs2/compress/Zip.scala#L64) causes all the bytes for each entry to be read into memory, which can lead to out-of-memory errors for large entries.

I believe the main limitation/reason for why this is necessary is so `tarEntry.setSize` can be called with the correct size. I tried using `chunks` instead of `chunkAll` along with updating the size with each chunk, but it didn't work properly because `tarOutputStream.putArchiveEntry(tarEntry)` is executed while the size is still `0`, so I ended up with an error when writing to `tarOutputStream`.

Can you think of any other ways to work around this? Here's my attempt in case it's helpful: https://github.com/lhns/fs2-compress/compare/main...mrdziuban:tar-zip-read-into-memory

**Comment by lhns** [comment] 2024-01-05 18:04
Hi, yes this was a problem I encountered and sadly I don't think it can be resolved without buffering the entries somewhere. It needs to be documented however. The problem is that the entry size needs to be set before writing the entry because it is written into the entry header which has to be written first. Offering an api to buffer the file to disk might be an option.

**Closed** 2024-04-12 11:57 UTC
Labels: enhancement

**Comment by jakobmerrild** [comment] 2024-10-08 15:22
@lhns It should be possible to add a `ZipEntry` without knowing the size up front when the method is `ZipOutputStream.DEFLATED`. Will you accept a PR which changes the typing of the `ZipArchiver` to `Archiver[F, Option]`?

We would love to use this library to add `.zip` functionality to our `fs2.Stream`, but the requirement that we need to know the size of each zip entry up front makes this impossible for us at the moment.

**Comment by lhns** [comment] 2024-10-08 16:49
@jakobmerrild I am pretty sure that I tried with DEFLATED but I would love a solution to this. I don't mind the change from Archiver[F, Some] to Archiver[F, Option] in ZipArchiver if it works. Maybe there could be different types for different methods.

**Comment by lhns** [comment] 2024-10-11 22:08
fixed in [v2.2.0](https://github.com/lhns/fs2-compress/releases/tag/2.2.0)
